[versions]
appcompat = "1.7.0"
navigationKtx = "2.7.7"
preferenceKtx = "1.2.1"
material = "1.12.0"
ossLicensesParser = "1.0.0"
ossLicensesPlugin = "0.10.6"
junit = "4.13.2"
junitVersion = "1.2.1"
espressoCore = "3.6.1"
agp = "8.6.0"
kotlin = "1.9.24"
screengrab = "2.1.1"

[libraries]
androidx-appcompat = { module = "androidx.appcompat:appcompat", version.ref = "appcompat" }
androidx-navigation-fragment-ktx = { module = "androidx.navigation:navigation-fragment-ktx", version.ref = "navigationKtx" }
androidx-navigation-ui-ktx = { module = "androidx.navigation:navigation-ui-ktx", version.ref = "navigationKtx" }
androidx-preference-ktx = { module = "androidx.preference:preference-ktx", version.ref = "preferenceKtx" }
material = { module = "com.google.android.material:material", version.ref = "material" }
oss-licenses-parser = { module = "de.philipp-bobek:oss-licenses-parser", version.ref = "ossLicensesParser" }
oss-licenses-plugin = { module = "com.google.android.gms:oss-licenses-plugin", version.ref = "ossLicensesPlugin" }
junit = { group = "junit", name = "junit", version.ref = "junit" }
androidx-junit = { group = "androidx.test.ext", name = "junit", version.ref = "junitVersion" }
androidx-espresso-core = { group = "androidx.test.espresso", name = "espresso-core", version.ref = "espressoCore" }
screengrab = { group = "tools.fastlane", name = "screengrab", version.ref = "screengrab" }

[plugins]
androidApplication = { id = "com.android.application", version.ref = "agp" }
jetbrainsKotlinAndroid = { id = "org.jetbrains.kotlin.android", version.ref = "kotlin" }
